spark_application:
  spark_app_batch_name: 'batchApp'
  spark_app_stream_name: 'streamApp'
batch:
  delta_player_dir: '/home/tomas/Personal_projects/Aston_Villa/task_1/PlayerPerformanceData'
  delta_ball_dir: '/home/tomas/Personal_projects/Aston_Villa/task_1/BallData'
  delta_features_player_dir: '/home/tomas/Personal_projects/Aston_Villa/task_1/PlayerAggregations'
streaming:
  format: 'parquet'
  file_checkpoint: '/home/tomas/Personal_projects/Aston_Villa/task_2/ballStreamDataCheckpoint'
  file_dir: '/home/tomas/Personal_projects/Aston_Villa/task_2/ballStreamData'
  wait_for_termination: None
streaming_aggregation:
  aggregating_time_s: 5600
  wait_for_agg_s: 3